{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f234298f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def exploracion_basica(df):\n",
    "    print(\"=== EXPLORACIÓN BÁSICA DEL DATASET ===\")\n",
    "    print(\"\\nPrimeras filas:\")\n",
    "    print(df.head())\n",
    "    print(\"\\nÚltimas filas:\")\n",
    "    print(df.tail())\n",
    "    print(\"\\nNúmero de filas y columnas:\")\n",
    "    print(df.shape)\n",
    "    print(\"\\nInformación general del DataFrame:\")\n",
    "    print(df.info())\n",
    "    print(\"\\nEstadísticas descriptivas:\")\n",
    "    print(df.describe())\n",
    "    print(\"\\nColumnas:\")\n",
    "    print(list(df.columns))\n",
    "\n",
    "def frecuencias_categoricas(df, top=5):\n",
    "    print(\"=== FRECUENCIAS DE VARIABLES CATEGÓRICAS ===\")\n",
    "    columnas_categoricas = df.select_dtypes(include=\"O\")\n",
    "    \n",
    "    if columnas_categoricas.empty:\n",
    "        print(\"No hay columnas categóricas.\")\n",
    "        return\n",
    "    \n",
    "    for nombre_columna in columnas_categoricas.columns:\n",
    "        print(f\"\\nValores únicos para la columna: {nombre_columna.upper()}\")\n",
    "        print(df[nombre_columna].value_counts(dropna=False).reset_index().head(top))\n",
    "\n",
    "def identificar_nulos(df):\n",
    "    print(\"=== COLUMNAS CON VALORES NULOS ===\")\n",
    "    nulos_por_columna = df.isnull().sum()\n",
    "    nulos_por_columna = nulos_por_columna[nulos_por_columna > 0]\n",
    "    if nulos_por_columna.empty:\n",
    "        print(\"No se encontraron valores nulos en el dataset.\")\n",
    "    else:\n",
    "        print(nulos_por_columna)\n",
    "\n",
    "def imputar_nulos(df):\n",
    "    print(\"=== IMPUTACIÓN DE VALORES NULOS ===\")\n",
    "    \n",
    "    columnas_categoricas = df.select_dtypes(include='object').columns\n",
    "    for nombre_columna_categorica in columnas_categoricas:\n",
    "        if df[nombre_columna_categorica].isnull().sum() > 0:\n",
    "            df[nombre_columna_categorica].fillna(\"Unknown\", inplace=True)\n",
    "            print(f\"Nulos en '{nombre_columna_categorica}' imputados con 'Unknown'\")\n",
    "    \n",
    "    columnas_numericas = df.select_dtypes(include='number').columns\n",
    "    for nombre_columna_numerica in columnas_numericas:\n",
    "        if df[nombre_columna_numerica].isnull().sum() > 0:\n",
    "            media = df[nombre_columna_numerica].mean()\n",
    "            df[nombre_columna_numerica].fillna(media, inplace=True)\n",
    "            print(f\"Nulos en '{nombre_columna_numerica}' imputados con la media ({media:.2f})\")\n",
    "\n",
    "def detectar_duplicados(df):\n",
    "    numero_duplicados = df.duplicated().sum()\n",
    "    print(f\"Filas duplicadas completas en el dataset: {numero_duplicados}\")\n",
    "    if numero_duplicados > 0:\n",
    "        print(\"Aquí tienes las filas duplicadas:\")\n",
    "        print(df[df.duplicated()])\n",
    "\n",
    "def tipos_de_dato(df):\n",
    "    print(\"=== TIPOS DE DATO POR COLUMNA ===\")\n",
    "    print(df.dtypes)\n",
    "\n",
    "def contar_valores_unicos(df):\n",
    "    print(\"=== CANTIDAD DE VALORES ÚNICOS POR COLUMNA ===\")\n",
    "    valores_unicos = df.nunique()\n",
    "    print(valores_unicos)\n",
    "\n",
    "def resumen_medidas(df):\n",
    "    print(\"=== MEDIA, MEDIANA Y MODA DE VARIABLES NUMÉRICAS ===\")\n",
    "    \n",
    "    columnas_numericas = df.select_dtypes(include='number')\n",
    "    \n",
    "    if columnas_numericas.empty:\n",
    "        print(\"No hay columnas numéricas en el dataset.\")\n",
    "        return\n",
    "    \n",
    "    for nombre_columna in columnas_numericas.columns:\n",
    "        print(f\"\\nColumna: {nombre_columna}\")\n",
    "        media = columnas_numericas[nombre_columna].mean()\n",
    "        mediana = columnas_numericas[nombre_columna].median()\n",
    "        moda = columnas_numericas[nombre_columna].mode()\n",
    "        \n",
    "        print(f\"  Media: {media:.2f}\")\n",
    "        print(f\"  Mediana: {mediana}\")\n",
    "        if len(moda) == 1:\n",
    "            print(f\"  Moda: {moda[0]}\")\n",
    "        else:\n",
    "            print(f\"  Moda (varias): {list(moda)}\")\n",
    "\n",
    "def mostrar_estadisticas_descriptivas(df):\n",
    "    print(\"=== ESTADÍSTICAS DESCRIPTIVAS ===\")\n",
    "    \n",
    "    # Seleccionar solo columnas numéricas\n",
    "    columnas_numericas = df.select_dtypes(include='number')\n",
    "    \n",
    "    # Calcular describe() y redondear\n",
    "    resumen = columnas_numericas.describe().round(2)\n",
    "    \n",
    "    # Mostrar\n",
    "    display(resumen)"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
